---
- name: creating webserver and web packages
  hosts: webserver
  become: true
  vars:
       - firewall_pkg: firewalld
       - firewall_svc: firewalld
       - web_pkg: httpd
       - web_svc: httpd
       - ssl_pkg: mod_ssl
       - httpdconf_src: files/httpd.conf
       - httpdconf_dest: /etc/httpd/conf/httpd.conf
       - htaccess_src: files/.htaccess
       - secrets_dir: /etc/httpd/secrets
       - secrets_src: files/htpasswd
       - secrets_dest: "{{ secrets_dir }}/htpasswd"
       - web_root: /var/www/html

  tasks:
       - name:  install the necessary packages
         package:
                 name: 
                     - "{{ firewall_pkg }}"
                     - "{{ web_pkg }}"
                     - "{{ ssl_pkg }}"
                 state: latest

       - name: copying the content using copy module
         copy:
                 src: "{{ httpdconf_src }}"
                 dest: "{{ httpdconf_dest }}"
                 owner: root
                 group: root
                 mode: '0644'

       - name: create user
         user:
                 name: apache
                 group: apache

       - name: creating and setting permission for secrets folder
         file:
                 path: "{{ secrets_dir }}"
                 state: directory
                 owner: apache
                 group: apache
                 mode: '0500'

       - name: setting file permission for secrets file
         copy:
                 src: "{{ secrets_src }}"
                 dest: "{{ secrets_dest }}"
                 owner: apache
                 group: apache
                 mode: '0400'

       - name: create a htaccess file using module file
         copy:
                  src: "{{ htaccess_src }}"
                  dest: "{{ web_root }}/.htaccess"
                  owner: apache
                  group: apache
                  mode: "0400"

       - name: Create index.html file
         copy:
                  content: |
                      {{ ansible_fqdn }} ({{ ansible_default_ipv4.address }}) has been customized by Ansible.
                  dest: "{{ web_root }}/index.html"

       - name: start service firewall
         service:
                  name: firewalld
                  state: started
                  enabled: yes 

       - name: adding https service to firewall
         firewalld:
                  service: https
                  permanent: true
                  state: enabled

       - name: adding httpd service
         service:
                  name: "{{ web_svc }}"
                  state: started
                  enabled: yes

- name: second play for webserver
  hosts: localhost
  vars:
       web_user: guest
  vars_files:
     - /home/student/data-review/vars/secret.yml

  tasks:
       - name: Request content from serverb.lab.example.com
         uri:
                  url: https://serverb.lab.example.com
                  method: GET
                  force_basic_auth: yes
                  user: "{{ web_user }}"
                  password: "{{ web_pass }}"
                  validate_certs: no
                  return_content: yes
                  status_code: 200
         register: auth_test

       - name: Print content returned from the web server
         debug:
                  msg: auth_test.content   

